baseURL = 'https://otonatabi-hugo.pages.dev/'
languageCode = 'ja-jp'
title = '配当金でどこに行く？資産4200万円サイドFIRE５０代女子の旅手帖'
theme = "ananke"
mainSections = ["posts"]

[params]
  ananke_socials = false
  show_header_text = false
  custom_css = ["css/custom.css"]
  cover_dimming_class = "bg-black-50"
  background_color_class = "bg-near-white"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "旅行記"
  url = "/categories/%E6%97%85%E8%A1%8C%E8%A8%98/"
  weight = 1

[[menu.main]]
  name = "グルメ"
  url = "/categories/%E3%82%B0%E3%83%AB%E3%83%A1/"
  weight = 2

[[menu.main]]
  name = "株・投資"
  url = "/categories/%E6%A0%AA%E3%83%BB%E6%8A%95%E8%B3%87/"
  weight = 3

[[menu.main]]
  name = "おすすめアイテム"
  url = "/categories/%E3%81%8A%E3%81%99%E3%81%99%E3%82%81%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0/"
  weight = 4
